# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/jack/gitroot/autolua/LuaAutoC

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/jack/gitroot/autolua/LuaAutoC

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/gitroot/autolua/LuaAutoC/CMakeFiles /home/jack/gitroot/autolua/LuaAutoC/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/jack/gitroot/autolua/LuaAutoC/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game_srv

# Build rule for target.
game_srv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game_srv
.PHONY : game_srv

# fast build rule for target.
game_srv/fast:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/build
.PHONY : game_srv/fast

CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.o: CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.o

.PHONY : CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.o

# target to build an object file
CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.o
.PHONY : CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.o

CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.i: CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.i

.PHONY : CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.i

# target to preprocess a source file
CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.i
.PHONY : CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.i

CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.s: CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.s

.PHONY : CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.s
.PHONY : CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.c.s

CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

examples/example_basic.o: examples/example_basic.c.o

.PHONY : examples/example_basic.o

# target to build an object file
examples/example_basic.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_basic.c.o
.PHONY : examples/example_basic.c.o

examples/example_basic.i: examples/example_basic.c.i

.PHONY : examples/example_basic.i

# target to preprocess a source file
examples/example_basic.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_basic.c.i
.PHONY : examples/example_basic.c.i

examples/example_basic.s: examples/example_basic.c.s

.PHONY : examples/example_basic.s

# target to generate assembly for a file
examples/example_basic.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_basic.c.s
.PHONY : examples/example_basic.c.s

examples/example_convert.o: examples/example_convert.c.o

.PHONY : examples/example_convert.o

# target to build an object file
examples/example_convert.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_convert.c.o
.PHONY : examples/example_convert.c.o

examples/example_convert.i: examples/example_convert.c.i

.PHONY : examples/example_convert.i

# target to preprocess a source file
examples/example_convert.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_convert.c.i
.PHONY : examples/example_convert.c.i

examples/example_convert.s: examples/example_convert.c.s

.PHONY : examples/example_convert.s

# target to generate assembly for a file
examples/example_convert.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_convert.c.s
.PHONY : examples/example_convert.c.s

examples/example_embed.o: examples/example_embed.c.o

.PHONY : examples/example_embed.o

# target to build an object file
examples/example_embed.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_embed.c.o
.PHONY : examples/example_embed.c.o

examples/example_embed.i: examples/example_embed.c.i

.PHONY : examples/example_embed.i

# target to preprocess a source file
examples/example_embed.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_embed.c.i
.PHONY : examples/example_embed.c.i

examples/example_embed.s: examples/example_embed.c.s

.PHONY : examples/example_embed.s

# target to generate assembly for a file
examples/example_embed.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_embed.c.s
.PHONY : examples/example_embed.c.s

examples/example_enum.o: examples/example_enum.c.o

.PHONY : examples/example_enum.o

# target to build an object file
examples/example_enum.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_enum.c.o
.PHONY : examples/example_enum.c.o

examples/example_enum.i: examples/example_enum.c.i

.PHONY : examples/example_enum.i

# target to preprocess a source file
examples/example_enum.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_enum.c.i
.PHONY : examples/example_enum.c.i

examples/example_enum.s: examples/example_enum.c.s

.PHONY : examples/example_enum.s

# target to generate assembly for a file
examples/example_enum.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_enum.c.s
.PHONY : examples/example_enum.c.s

examples/example_func.o: examples/example_func.c.o

.PHONY : examples/example_func.o

# target to build an object file
examples/example_func.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_func.c.o
.PHONY : examples/example_func.c.o

examples/example_func.i: examples/example_func.c.i

.PHONY : examples/example_func.i

# target to preprocess a source file
examples/example_func.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_func.c.i
.PHONY : examples/example_func.c.i

examples/example_func.s: examples/example_func.c.s

.PHONY : examples/example_func.s

# target to generate assembly for a file
examples/example_func.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_func.c.s
.PHONY : examples/example_func.c.s

examples/example_mod.o: examples/example_mod.c.o

.PHONY : examples/example_mod.o

# target to build an object file
examples/example_mod.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_mod.c.o
.PHONY : examples/example_mod.c.o

examples/example_mod.i: examples/example_mod.c.i

.PHONY : examples/example_mod.i

# target to preprocess a source file
examples/example_mod.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_mod.c.i
.PHONY : examples/example_mod.c.i

examples/example_mod.s: examples/example_mod.c.s

.PHONY : examples/example_mod.s

# target to generate assembly for a file
examples/example_mod.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_mod.c.s
.PHONY : examples/example_mod.c.s

examples/example_struct.o: examples/example_struct.c.o

.PHONY : examples/example_struct.o

# target to build an object file
examples/example_struct.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_struct.c.o
.PHONY : examples/example_struct.c.o

examples/example_struct.i: examples/example_struct.c.i

.PHONY : examples/example_struct.i

# target to preprocess a source file
examples/example_struct.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_struct.c.i
.PHONY : examples/example_struct.c.i

examples/example_struct.s: examples/example_struct.c.s

.PHONY : examples/example_struct.s

# target to generate assembly for a file
examples/example_struct.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_struct.c.s
.PHONY : examples/example_struct.c.s

examples/example_unnested.o: examples/example_unnested.c.o

.PHONY : examples/example_unnested.o

# target to build an object file
examples/example_unnested.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_unnested.c.o
.PHONY : examples/example_unnested.c.o

examples/example_unnested.i: examples/example_unnested.c.i

.PHONY : examples/example_unnested.i

# target to preprocess a source file
examples/example_unnested.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_unnested.c.i
.PHONY : examples/example_unnested.c.i

examples/example_unnested.s: examples/example_unnested.c.s

.PHONY : examples/example_unnested.s

# target to generate assembly for a file
examples/example_unnested.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/example_unnested.c.s
.PHONY : examples/example_unnested.c.s

examples/test.o: examples/test.c.o

.PHONY : examples/test.o

# target to build an object file
examples/test.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/test.c.o
.PHONY : examples/test.c.o

examples/test.i: examples/test.c.i

.PHONY : examples/test.i

# target to preprocess a source file
examples/test.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/test.c.i
.PHONY : examples/test.c.i

examples/test.s: examples/test.c.s

.PHONY : examples/test.s

# target to generate assembly for a file
examples/test.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/examples/test.c.s
.PHONY : examples/test.c.s

lautoc.o: lautoc.c.o

.PHONY : lautoc.o

# target to build an object file
lautoc.c.o:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/lautoc.c.o
.PHONY : lautoc.c.o

lautoc.i: lautoc.c.i

.PHONY : lautoc.i

# target to preprocess a source file
lautoc.c.i:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/lautoc.c.i
.PHONY : lautoc.c.i

lautoc.s: lautoc.c.s

.PHONY : lautoc.s

# target to generate assembly for a file
lautoc.c.s:
	$(MAKE) -f CMakeFiles/game_srv.dir/build.make CMakeFiles/game_srv.dir/lautoc.c.s
.PHONY : lautoc.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... game_srv"
	@echo "... edit_cache"
	@echo "... CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.o"
	@echo "... CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.i"
	@echo "... CMakeFiles/3.16.2/CompilerIdC/CMakeCCompilerId.s"
	@echo "... CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.16.2/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... examples/example_basic.o"
	@echo "... examples/example_basic.i"
	@echo "... examples/example_basic.s"
	@echo "... examples/example_convert.o"
	@echo "... examples/example_convert.i"
	@echo "... examples/example_convert.s"
	@echo "... examples/example_embed.o"
	@echo "... examples/example_embed.i"
	@echo "... examples/example_embed.s"
	@echo "... examples/example_enum.o"
	@echo "... examples/example_enum.i"
	@echo "... examples/example_enum.s"
	@echo "... examples/example_func.o"
	@echo "... examples/example_func.i"
	@echo "... examples/example_func.s"
	@echo "... examples/example_mod.o"
	@echo "... examples/example_mod.i"
	@echo "... examples/example_mod.s"
	@echo "... examples/example_struct.o"
	@echo "... examples/example_struct.i"
	@echo "... examples/example_struct.s"
	@echo "... examples/example_unnested.o"
	@echo "... examples/example_unnested.i"
	@echo "... examples/example_unnested.s"
	@echo "... examples/test.o"
	@echo "... examples/test.i"
	@echo "... examples/test.s"
	@echo "... lautoc.o"
	@echo "... lautoc.i"
	@echo "... lautoc.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

